language: node_js
node_js:
- '0.10'
env:
  global:
    secure: radR/rowNe64+BfZoD/9jH5owfKnjLz1KM2Dns3G7K9vyL9b2pQUJ37wZ8p68iAWj8BS7izn0nBEXzV/W0P2D9iFpaQ1zdZCpwMhfXg7eeAjYaEi5eVSPzZkxPggHdcRZvV0OFj9CTTGbgesqO2vCEPHx0UqOhn40i3td7s+aNk=

before_script:
- npm install -g grunt-cli
after_success: 
- "grunt docs"
